







name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t myapp .

      - name: SCP Files & SSH to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            cd /home/ubuntu/app
            git pull
            docker build -t myapp .
            docker run -d -p 80:80 --name myapp myapp
